main: dev.dungeoncrawler.DungeonCrawler
name: DungeonCrawler
version: 1.0-SNAPSHOT
authors:
  - Xwy
  - ImUnsmart
commands:
  spawn:
    permission: dungeoncrawler.spawn
  set:
    permission: dungeoncrawler.admin
  loot:
    permission: dungeoncrawler.loot
  pet:
    permission: dungeoncrawler.pet
  balance:
    aliases:
      - bal
  party:
    aliases:
      - p