main: dev.dungeoncrawler.DungeonCrawler
name: DungeonCrawler
version: 1.0-SNAPSHOT
authors:
  - Xwy
  - ImUnsmart
commands:
  spawn:
    permission: dungeoncrawler.spawn
  set:
    permission: dungeoncrwaler.admin
  balance:
    aliases:
      - bal
  party:
    aliases:
      - p